export const USER_STATE_CHANGE = "USER_STATE_CHANGE";

export const CURRENT_USER_POSTS_UPDATE = "CURRENT_USER_POSTS_UPDATE";
export const CHATS_SET = "CHATS_SET";

export const MODAL_OPEN_COMMENT_SECTION = "MODAL_OPEN_COMMENT_SECTION";
export const MODAL_OPEN_HOME_PLUS_SECTION = "MODAL_OPEN_HOME_PLUS_SECTION";
export const MODAL_OPEN_HOME_ADD_PIC_AND_VIDEO_PLUS =
  "MODAL_OPEN_HOME_ADD_PIC_AND_VIDEO_PLUS";

export const CLEAR_MODAL = "CLEAR_MODAL";

export const ADD_PIC_AND_VIDEO = "ADD_PIC_AND_VIDEO";
export const REMOVE_PIC_AND_VIDEO = "REMOVE_PIC_AND_VIDEO";
export const CLEAR_ALL_PIC_AND_VIDEO = "CLEAR_ALL_PIC_AND_VIDEO";

export const DISPLAY_USER_POST_PRODUCT = "DISPLAY_USER_POST_PRODUCT";

export const CART = "CART";

export const LOADING = "LOADING";

export const LOAD_ROOM = "LOAD_ROOM";
export const LOAD_ROOM_ID = "LOAD_ROOM_ID";